### ISSUE TITLE
建议：将项目拆分为库和控制台工具，以提高模块化和价值

### ISSUE THREAD

**Issue by sangyuxiaowu** [soryu-ryouji/EpubBuilder#1]
最近在做一个电子书下载的应用，然后在书籍打包为了节省空间，我考虑加入epub格式，在搜寻可用类库。发现了您通过命令行创建 Epub 电子书的项目，我觉得这是个很棒的想法！但是，我有一个建议，我相信这可以改进项目，并为用户提供更多价值。

我建议将项目分为两个独立的部分：
1. 编辑和阅读 Epub 文件的库：这将允许开发人员轻松地将 Epub 编辑和阅读功能集成到他们的应用程序中，而无需使用命令行工具。这也将使其他人更容易为库做出贡献并改进其功能。
2. 创建 Epub 文件的控制台工具：通过将控制台工具与库分开，您可以为只想创建 Epub 文件而无需深入了解代码的用户提供一个简洁的界面。

将项目拆分为库和控制台工具将带来以下好处：
1. 改进的模块化：开发人员可以根据自己的需求选择使用库或控制台工具。
2. 更容易的协作：其他开发人员可以独立地为库或控制台工具做出贡献。
3. 更大的价值：通过提供库，发布到Nuget，可以让更多的用户发现，您将使其他开发人员能够创建利用您的代码的新应用程序，从而增加项目的整体价值。

我希望您考虑这个建议，因为我相信这将大大改善项目并为用户提供更多价值。感谢您花时间和精力创建这个有用的工具！

祝好

**Comment by soryu-ryouji** [comment]
非常感谢您的建议，将EpubBuilder项目拆分为库和交互界面两部分将是我下一步的工作。
